### ISSUE TITLE
TimeZone issue

### ISSUE THREAD

**Issue by ventisep** [ventisep/RowTime#12]
using on iphone in geneva the delta time had a whole day added to it wen testing past midnight.  why? how to fix.

**Comment by AlexVentisei** [comment]
that sounds like an issue, is that because of the global time coordinates changing. (but I don't think rowers will be rowing that far anyway, so we just need a way for the start and stop time to be equally adjusted in a different country)

**Comment by ventisep** [comment]
think it was because the server time is
